all:
  hosts:
    web1.example.com:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    web2.example.com:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    db1.example.com:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
  children:
    web:
      hosts:
        web1.example.com: {}
        web2.example.com: {}
    db:
      hosts:
        db1.example.com: {}
